version: "3.7"

services:
  elasticsearch:
    # Error - Caused by: java.nio.file.AccessDeniedException: /usr/share/elasticsearch/data/nodes
    # sudo sysctl -w vm.max_map_count=262144;

    # chmod for elastic volume
    # sudo mkdir -p ./docker/elasticsearch/data;
    # sudo chmod 777 ./docker/elasticsearch/data;
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - ./docker/elasticsearch/data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    ulimits:
      memlock:
        soft: -1
        hard: -1
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - xpack.security.transport.ssl.enabled=false
